Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProyectoºMVC.Models;
using System.Web.Mvc;
using Rotativa;
using System.IO;
using System.Web.Routing;
namespace ProyectoºMVC.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.cliente.ToList());
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(cliente cliente)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.cliente.Add(cliente);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", "error " + ex);
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.cliente.Find(id));
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var findUser = db.cliente.Find(id);
                    db.cliente.Remove(findUser);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    cliente findUser = db.cliente.Where(a => a.id == id).FirstOrDefault();
                    return View(findUser);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(cliente editUser)
        {
            try
            {

                using (var db = new inventario2021Entities1())
                {
                    cliente user = db.cliente.Find(editUser.id);

                    user.nombre = editUser.nombre;
                    user.documento = editUser.documento;
                    user.email = editUser.email;


                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        public ActionResult uploadCSV()
        {
            return View();
        }

        [HttpPost]
        public ActionResult uploadCSV(HttpPostedFileBase fileForm)
        {
            try
            {

               
                string filePath = string.Empty;

              
                if (fileForm != null)
                {
                   
                    string path = Server.MapPath("~/Uploads/");

                    
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                 
                    filePath = path + Path.GetFileName(fileForm.FileName);

                    
                    string extension = Path.GetExtension(fileForm.FileName);

                    
                    fileForm.SaveAs(filePath);

                    string csvData = System.IO.File.ReadAllText(filePath);

                    foreach (string row in csvData.Split('\n'))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            var newCliente = new cliente
                            {
                                nombre = row.Split(';')[0],
                                documento = row.Split(';')[1],
                                email = row.Split(';')[2],
                                
                            };

                            using (var db = new inventario2021Entities1())
                            {
                                db.cliente.Add(newCliente);
                                db.SaveChanges();
                            }
                        }
                    }
                }

                return View();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        public ActionResult ReporteCliente()
        {
            try
            {
                var db = new inventario2021Entities1();
                var query = from tablaCliente in db.cliente
                            join tablaCompra in db.compra on tablaCliente.id equals tablaCompra.id_cliente
                            select new ReporteCliente
                            {
                                nombreCliente = tablaCliente.nombre,
                                documentoCliente = tablaCliente.documento,
                                totalCompra = tablaCompra.total,
                                fecha_Compra=tablaCompra.fecha,
                                idUsuario = tablaCompra.id_usuario


                            };
                return View(query);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }
        public ActionResult PdfReporte()
        {
            return new ActionAsPdf("ReporteCliente") { FileName = "reporte.pdf" };
        }
        public ActionResult PaginadorIndex(int pagina = 1)
        {
            try
            {
                var cantidadRegistros = 5;

                using (var db = new inventario2021Entities1())
                {
                    var Clientes = db.cliente.OrderBy(x => x.id).Skip((pagina - 1) * cantidadRegistros).Take(cantidadRegistros).ToList();

                    var totalRegistros = db.cliente.Count();
                    var modelo = new ClienteIndex();
                    modelo.clientes = Clientes;
                    modelo.ActualPage = pagina;
                    modelo.Total = totalRegistros;
                    modelo.RecordsPage = cantidadRegistros;
                    modelo.valueQueryString = new RouteValueDictionary();

                    return View(modelo);
                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

    }

}

Controllers/CompraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProyectoºMVC.Models;
using System.Web.Mvc;

namespace ProyectoºMVC.Controllers
{
    public class CompraController : Controller
    {
        // GET: Compra
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.compra.ToList());
            }

        }
        public  ActionResult ListaCliente()
        {
            using (var db = new inventario2021Entities1())
            
                return PartialView(db.cliente.ToList());
            

        }
        public ActionResult ListaUsuario()
        {
            
            using (var db=new inventario2021Entities1())
              
              return PartialView(db.usuario.ToList());
              
           
                
            
        }
        public static string NombreUsuario(int NomUsu)
        {
            using (var db = new inventario2021Entities1())
            {
                return db.usuario.Find(NomUsu).nombre;
            }
        }
        public static string NombreCliente(int NomCli)
        {
            using (var db = new inventario2021Entities1())
            {
                return db.cliente.Find(NomCli).nombre;
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(compra compra)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.compra.Add(compra);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", "error " + ex);
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                var findUser = db.compra.Find(id);
                return View(findUser);
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var findUser = db.compra.Find(id);
                    db.compra.Remove(findUser);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    compra findUser = db.compra.Where(a => a.id == id).FirstOrDefault();
                    return View(findUser);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(compra editUser)
        {
            try
            {

                using (var db = new inventario2021Entities1())
                {
                    compra user = db.compra.Find(editUser.id);

                    user.fecha= editUser.fecha;
                    user.total = editUser.total;
                    user.id_usuario = editUser.id_usuario;
                    user.id_cliente = editUser.id_cliente;
                   

                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }


        }
    }

}

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProyectoºMVC.Models;
using System.Web.Mvc;

namespace ProyectoºMVC.Controllers
{
    public class RolesController : Controller
    {
        // GET: Roles
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.roles.ToList());
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(roles roles)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.roles.Add(roles);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", "error " + ex);
                return View();
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var findUser = db.roles.Find(id);
                    db.roles.Remove(findUser);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                var findUser = db.roles.Find(id);
                return View(findUser);
            }
        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    roles findUser = db.roles.Where(a => a.id == id).FirstOrDefault();
                    return View(findUser);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(roles editUser)
        {
            try
            {

                using (var db = new inventario2021Entities1())
                {
                    roles user = db.roles.Find(editUser.id);

                    user.descripcion = editUser.descripcion;

                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }
    }

}

Views/Shared/Paginador.cshtml
@model ProyectoºMVC.Models.BaseModelo

@{ var cantidadPaginas = (int)Math.Ceiling((double)Model.Total / Model.RecordsPage); }

<ul>
    @if (Model.ActualPage == 1)
    {
        Model.valueQueryString["pagina"] = 1;
<li class="disabled">@Html.ActionLink("Anterior", null, Model.valueQueryString)</li> }
            else
            {
                Model.valueQueryString["pagina"] = Model.ActualPage - 1;
<li class="">@Html.ActionLink("Anterior", null, Model.valueQueryString)</li>}

    @if (Model.ActualPage == cantidadPaginas)
    {
        Model.valueQueryString["pagina"] = cantidadPaginas;
<li class="disabled">@Html.ActionLink("Siguiente", null, Model.valueQueryString)</li> }
            else
            {
                Model.valueQueryString["pagina"] = Model.ActualPage + 1;
<li class="">@Html.ActionLink("Siguiente", null, Model.valueQueryString)</li>}

</ul>

@{ int Inicial = 1;
                var radio = 3;
                var cantidadMaximaDePaginas = radio * 2 - 1;
                int Final = (cantidadPaginas > cantidadMaximaDePaginas) ? cantidadMaximaDePaginas : cantidadPaginas;

                if (Model.ActualPage > radio + 1)
                {
                    Inicial = Model.ActualPage - radio;

                    if (cantidadPaginas > Model.ActualPage + radio)
                    {
                        Final = Model.ActualPage + radio;
                    }
                    else
                    {
                        Final = cantidadPaginas;
                    }
                } }

<ul class="pagination">
    @{Model.valueQueryString["pagina"] = 1; }

    <li>@Html.ActionLink("Primera", null, Model.valueQueryString)</li>
    @for (int i = Inicial; i <= Final; i++)
    {
        Model.valueQueryString["pagina"] = i;
        if (i == Model.ActualPage)
        {
<li class="active">@Html.ActionLink(i.ToString(), null, Model.valueQueryString)</li> }
                else
                {
<li>@Html.ActionLink(i.ToString(), null, Model.valueQueryString)</li>}
            }
    @{Model.valueQueryString["pagina"] = cantidadPaginas; }
    <li>@Html.ActionLink("Ultima", null, Model.valueQueryString)</li>
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ProyectoºMVC</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/Estilos.css")
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Inventario 2021", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated == false) 
                    { 

                        <li>@Html.ActionLink("Ingresar", "Login", "Usuario")</li>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {

                        <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Opciones
                                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Usuario Crud", "Index", "Usuario")</li>
                                <li>@Html.ActionLink("Cliente Crud", "Index", "Cliente")</li>
                                <li>@Html.ActionLink("Proveedor Crud", "Index", "Proveedor")</li>
                                <li>@Html.ActionLink("Producto Crud", "Index", "Producto")</li>
                                <li>@Html.ActionLink("Roles Crud", "Index", "Roles")</li>
                                <li>@Html.ActionLink("Compra Crud", "Index", "Compra")</li>
                                <li>@Html.ActionLink("Producto Compra Crud", "Index", "Producto_compra")</li>
                                <li>@Html.ActionLink("Producto imagen Crud", "Index", "Producto_Imagen")</li>
                                <li>@Html.ActionLink("Usuario Roles", "Index", "Usuario_Rol")</li>

                            </ul>
                        </li>
                        <li class="dropdown">

                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                Reportes
                                <span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
                            </a>
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Reporte Proveedor-Producto", "Reporte", "Producto")</li>
                                <li>@Html.ActionLink("Reporte Cliente-Compra", "ReporteCliente", "Cliente")</li>

                            </ul>
                        </li>

                        <li>@Html.ActionLink("Cerrar Sesion", "CloseSession", "Usuario")</li>
                    }
                    


</div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi Proyecto ASP</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>