Models/producto.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoºMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.producto_imagen = new HashSet<producto_imagen>();
            this.producto_compra = new HashSet<producto_compra>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "El campo  Nombre es obligatorio")]
        public string nombre { get; set; }
        [Required(ErrorMessage = "El campo Precio_Unitario es obligatorio")]
        public int percio_unitario { get; set; }
        [Required(ErrorMessage = "El campo  Descripcion es obligatorio")]
        public string descripcion { get; set; }
        [Required(ErrorMessage = "El campo Cantidad es obligatorio")]
        public int cantidad { get; set; }
        [Required(ErrorMessage = "El campo Id_Proveedor es obligatorio")]
        public int id_proveedor { get; set; }
       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_imagen> producto_imagen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<producto_compra> producto_compra { get; set; }
        public virtual proveedor proveedor { get; set; }
    }
}

Models/producto_imagen.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoºMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class producto_imagen
    {
        public int id { get; set; }
        [Required(ErrorMessage = "El campo Imagen  es obligatorio")]
        public string imagen { get; set; }
        [Required(ErrorMessage = "El campo Id_Producto  es obligatorio")]
        public int id_producto { get; set; }
    
        public virtual producto producto { get; set; }
    }
}

Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProyectoºMVC.Models;
using System.Web.Mvc;
using Rotativa;

namespace ProyectoºMVC.Controllers
{
    public class ProductoController : Controller
    {
        // GET: Producto
        public ActionResult Index()
            
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.producto.ToList());
            }
                
        }
   
        public static string NombreProveedor(int idProveedor)
        {
            using (var db = new inventario2021Entities1())
            {
               return db.proveedor.Find(idProveedor).nombre;
            }

        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(producto producto)
        {
            if (!ModelState.IsValid)
                return View();

            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.producto.Add(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        public ActionResult ListarProveedores()
        {
            using (var db = new inventario2021Entities1())
            {
                return PartialView(db.proveedor.ToList());
            }
        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.producto.Find(id));
            }
        }

        public ActionResult Edit(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                producto productoEdit = db.producto.Where(a => a.id == id).FirstOrDefault();
                return View(productoEdit);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(producto productoEdit)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var producto = db.producto.Find(productoEdit.id);
                    producto.nombre = productoEdit.nombre;
                    producto.cantidad = productoEdit.cantidad;
                    producto.descripcion = productoEdit.descripcion;
                    producto.percio_unitario = productoEdit.percio_unitario;
                    producto.id_proveedor = productoEdit.id_proveedor;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    producto producto = db.producto.Find(id);
                    db.producto.Remove(producto);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }
        }
        public ActionResult Reporte()
        {
            try
            {
                var db = new inventario2021Entities1();
                var query = from tablaProveedor in db.proveedor
                            join tablaProducto in db.producto on tablaProveedor.id equals tablaProducto.id_proveedor
                            select new Reporte
                            {
                                nombreProveedor = tablaProveedor.nombre,
                                telefonoProveedor = tablaProveedor.telefono,
                                direccionProveedor = tablaProveedor.direccion,
                                nombreProducto = tablaProducto.nombre,
                                precioProducto = tablaProducto.percio_unitario
                            };
                return View(query);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }
        public ActionResult PdfProducto()
        {
            return new ActionAsPdf("Reporte") { FileName = "reporte.pdf" };
        }
    }
}

Controllers/Producto_ImagenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ProyectoºMVC.Models;
using System.Web.Mvc;
using System.IO;

namespace ProyectoºMVC.Controllers
{
    public class Producto_ImagenController : Controller
    {
        // GET: Producto_Imagen
        public ActionResult Index()
        {
            using (var db = new inventario2021Entities1())
            {
                return View(db.producto_imagen.ToList());
            }
        }
        public ActionResult CargarImagen()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CargarImagen(int producto, HttpPostedFileBase imagen)
        {
            try
            {
                //string para guardar la ruta
                string filePath = string.Empty;
                string nameFile = "";

                //condicion para saber si el archivo llego
                if (imagen != null)
                {
                    //ruta de la carpeta que guardara el archivo
                    string path = Server.MapPath("~/Uploads/Imagenes/");

                    //condicion para saber si la carpeta uploads existe
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    nameFile = Path.GetFileName(imagen.FileName);

                    //obtener el nombre del archivo
                    filePath = path + Path.GetFileName(imagen.FileName);

                    //obtener la extension del archivo
                    string extension = Path.GetExtension(imagen.FileName);

                    //guardar el archivo
                    imagen.SaveAs(filePath);
                }

                using (var db = new inventario2021Entities1())
                {
                    var imagenProducto = new producto_imagen();
                    imagenProducto.id_producto = producto;
                    imagenProducto.imagen = "/Uploads/Imagenes/" + nameFile;
                    db.producto_imagen.Add(imagenProducto);
                    db.SaveChanges();

                }

                return View();

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }

        public ActionResult Productos()
        {

            using (var db = new inventario2021Entities1())

                return PartialView(db.producto.ToList());




        }
        public static string NombreProducto(int NomPro)
        {
            using (var db = new inventario2021Entities1())
            {
                return db.producto.Find(NomPro).nombre;
            }
        }
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(producto_imagen producto_imagen)
        {
            if (!ModelState.IsValid)
                return View();
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    db.producto_imagen.Add(producto_imagen);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(" ", "error " + ex);
                return View();
            }
        }
        public ActionResult Details(int id)
        {
            using (var db = new inventario2021Entities1())
            {
                var findUser = db.producto_imagen.Find(id);
                db.producto_imagen.Remove(findUser);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
        }
        public ActionResult Delete(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    var findUser = db.producto_imagen.Find(id);
                    db.producto_imagen.Remove(findUser);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Error" + ex);
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            try
            {
                using (var db = new inventario2021Entities1())
                {
                    producto_imagen findUser = db.producto_imagen.Where(a => a.id == id).FirstOrDefault();
                    return View(findUser);
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error" + ex);
                return View();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(producto_imagen editUser)
        {
            try
            {

                using (var db = new inventario2021Entities1())
                {
                    producto_imagen user = db.producto_imagen.Find(editUser.id);

                    user.imagen = editUser.imagen;
                    user.id_producto = editUser.id_producto;
                 


                    db.SaveChanges();
                    return RedirectToAction("Index");

                }

            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "error " + ex);
                return View();
            }

        }

    }
}

Views/Producto_Imagen/CargarImagen.cshtml
@model IEnumerable<ProyectoºMVC.Models.producto_imagen>
<h2>Cargar Imagen Producto</h2>

@using (Html.BeginForm("CargarImagen", "Producto_Imagen", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
@Html.AntiForgeryToken()
                <div class="form-group">
                    <label class="control-label col-md-2"for="id_Producto">Producto</label>
                    <div class="col-md-10">
                   @Html.Action("Productos")
                    </div>
                </div>

                         <div class="form-group">
                            <label class="control-label col-md-2">Imagen</label>
                                 <div class="col-md-10">
                                  <input type="file" name="imagen" class="form-control" />
                           </div>
                        </div>

         <div class="form-group">
           <div class="col-md-10">
             <input type="submit" value="Enviar" class="form-control" />
          </div>
     </div>
}

Views/Producto_Imagen/Create.cshtml
@model ProyectoºMVC.Models.producto_imagen

@{
    ViewBag.Title = "Crear Producto Imagen";
}

<h2>Crear Producto Imagen</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>producto_imagen</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_producto, "id_producto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("Productos")
                @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Crear Producto" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index")
</div>

Views/Producto_Imagen/Delete.cshtml
@model ProyectoºMVC.Models.producto_imagen

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>producto_imagen</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto.nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Producto_Imagen/Details.cshtml
@model ProyectoºMVC.Models.producto_imagen

@{
    ViewBag.Title = "Deatalles";
}

<h2>Deatalles</h2>

<div>
    <h4>producto_imagen</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.imagen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.imagen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto.nombre)
        </dt>

        <dd>
            @ProyectoºMVC.Controllers.Producto_ImagenController.NombreProducto(Model.id_producto)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Regresar a la lista","Index")
</p>

Views/Producto_Imagen/Edit.cshtml
@model ProyectoºMVC.Models.producto_imagen

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>producto_imagen</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.imagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_producto, "id_producto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Action("Productos")
                @Html.ValidationMessageFor(model => model.id_producto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Actualizar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Views/Producto_Imagen/Index.cshtml
@model IEnumerable<ProyectoºMVC.Models.producto_imagen>

@{
    ViewBag.Title = "Lista Producto";
}

<h2>Lista Producto Imagen</h2>

<p>
    @Html.ActionLink("Crear Producto", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.imagen)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.producto.nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.imagen)
        </td>
        <td>

            @ProyectoºMVC.Controllers.Producto_ImagenController.NombreProducto(item.id_producto);
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.id }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.id }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

Views/Producto_Imagen/Productos.cshtml
@model IEnumerable<ProyectoºMVC.Models.producto>

<select class="form-control" id="id_Producto" name="id_Producto">
    @foreach (var item in Model)
    {
<option value="@item.id">@item.nombre</option>}
</select>